export  const  testDB = [{
    id:'1',
    restName:'maks corndogs',
    dishName:'stuffed corndogs',
    description:'it was very tasty',
    image:'https://i.pinimg.com/564x/40/30/bb/4030bb3e7b0364b0718d90a5d2a14601.jpg',
    tags:['spicy'],
    link:'www.google.ca',
    price:'10',
    fillingness:'50',

},
{
    id:'2',
    restName:'fuwa fuwa',
    dishName:'cloud cakes',
    description:'soft and delicious',
    image:'https://i.pinimg.com/564x/4f/52/b9/4f52b90f7206d2171e248efd078341aa.jpg',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'14',
    fillingness:'30',
},{
    id:'3',
    restName:'frans',
    dishName:'guac toast',
    description:'it was very tasty',
    image:'https://i.pinimg.com/564x/55/2c/f4/552cf482595bff449693402842bb32c8.jpg',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'8',
    fillingness:'30',
},{
    id:'4',
    restName:'aroma',
    dishName:'spiced chicken bowl',
    description:'it was very tasty',
    image:'https://i.pinimg.com/564x/f5/9e/bc/f59ebcf060f6e184e195f469e87fe3cc.jpg',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'18',
    fillingness:'50',
},{
    id:'5',
    restName:'ai sushi',
    dishName:'assorted rolls (30)',
    description:'it was very tasty',
    image:'https://i.pinimg.com/564x/ef/ca/26/efca2616e091e0d86892c94961c0be61.jpg',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'6',
    restName:'baos r us',
    dishName:'pork buns',
    description:'it was very tasty',
    image:'https://i.pinimg.com/564x/77/2b/10/772b10d66477db2725d569b84109a9ad.jpg',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'7',
    restName:'taco2sdays',
    dishName:'barbacoa tacos',
    description:'it was very tasty',
    image:'https://i.pinimg.com/564x/a3/88/1f/a3881f4c24cb9c5be03fb7a53810c53f.jpg',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'8',
    restName:'shanghi',
    dishName:'xiao long baos',
    description:'it was very tasty',
    image:'https://i.pinimg.com/564x/c8/b0/0c/c8b00c117d794dd0f1a2b16eb6020ffb.jpg',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'9',
    restName:'pancake island',
    dishName:'breakfast special 3',
    description:'it was very tasty',
    image:'https://i.pinimg.com/564x/08/e0/f6/08e0f6844a036a1456b1c1a197ee0875.jpg',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'10',
    restName:'Richards',
    dishName:'Katsu',
    description:'it was very tasty',
    image:'https://picsum.photos/200',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'11',
    restName:'raman city',
    dishName:'pork tonkatsu ramen',
    description:'it was very tasty',
    image:'https://i.pinimg.com/564x/67/bb/45/67bb459686a411be5928559827b01728.jpg',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'12',
    restName:'soup4dayz',
    dishName:'tomato soup',
    description:'it was very tasty',
    image:'https://i.pinimg.com/564x/d0/a4/ed/d0a4ed489d6a38c91c93333e79a9f51f.jpg',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'13',
    restName:'Richards',
    dishName:'Katsu',
    description:'it was very tasty',
    image:'https://picsum.photos/200',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'14',
    restName:'Richards',
    dishName:'Katsu',
    description:'it was very tasty',
    image:'https://picsum.photos/200',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'15',
    restName:'Richards',
    dishName:'Katsu',
    description:'it was very tasty',
    image:'https://picsum.photos/200',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'16',
    restName:'Richards',
    dishName:'Katsu',
    description:'it was very tasty',
    image:'https://picsum.photos/200',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'17',
    restName:'Richards',
    dishName:'Katsu',
    description:'it was very tasty',
    image:'https://picsum.photos/200',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'18',
    restName:'Richards',
    dishName:'Katsu',
    description:'it was very tasty',
    image:'https://picsum.photos/200',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'19',
    restName:'Richards',
    dishName:'Katsu',
    description:'it was very tasty',
    image:'https://picsum.photos/200',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},{
    id:'20',
    restName:'Richards',
    dishName:'Katsu',
    description:'it was very tasty',
    image:'https://picsum.photos/200',
    tags:['not spicy','cool'],
    link:'www.google.ca',
    price:'$$$',
    fillingness:'100',
},
]